# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6c6ca95a3d3dd579b693218899cfa2e81901c41913da73a751b8fb025e172b4502a2ebae405f6b178b348c5a5177ec4d1e00ceece310255b302bd672e3d4cd24

test:
  secret_key_base: d21d5bee296b37655ffa93cdea5b44c6738f85a6d14450281a3d94727c18873379be0df6f3797f358707c2ba7ecc81869ec704d034969950dbd149b1d07aae50

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
